authentication/urls.py
# authentication/urls.py

from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('register/', views.sign_up, name='sign_up'),
    # otras URL de autenticación si las tienes
]

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include("polls.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # URLs de autenticación proporcionadas por Django
    path('sign_up/', include('authentication.urls')),  # Incluye las URLs de la aplicación de autenticación
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    # ex: /polls/
    path("", views.IndexView.as_view(), name="index"),
    # ex: /polls/5/
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # ex: /polls/5/results/
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
]
urlpatterns += [
    path('myquestions/', views.QuestionByUserListView.as_view(), name='myquestions'),
]

authentication/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    CATEGORY_CHOICES = [
        ('A', 'General'),
        ('B', 'Technical'),
        ('C', 'Personal'),
    ]

    DAYS_RECENT = 7  # Configura el número de días para was_published_recently

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    created_at = models.DateTimeField("date created", default=timezone.now, editable=False)
    updated_at = models.DateTimeField("date updated", default=timezone.now)
    comment = models.TextField(blank=True, null=True)  # Campo opcional de tipo texto
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='A')
    pollster = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=self.DAYS_RECENT) <= self.pub_date <= now
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    created_at = models.DateTimeField("date created", default=timezone.now, editable=False)
    updated_at = models.DateTimeField("date updated", default=timezone.now)

    def __str__(self):
        return self.choice_text

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'}),

    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your username'}),
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'}),
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm your password'}),
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

authentication/views.py
# authentication/views.py

from .forms import RegistrationForm
from django.contrib.auth import login
from django.shortcuts import render, redirect

def sign_up(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = RegistrationForm()
    
    return render(request, 'authentication/register.html', {'form': form})

home/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'home/index.html')

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from .models import Question, Choice
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
               :5
               ]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

class QuestionByUserListView(LoginRequiredMixin,generic.ListView):
    """
    Vista genérica basada en clases que enumera las preguntas asignadas al usuario actual.
    """
    model = Question
    template_name='polls/questions_list_pollsters_user.html'
    paginate_by = 10

    def get_queryset(self):
        return Question.objects.filter(pollster=self.request.user).order_by('pub_date')

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

authentication/templates/authentication/register.html
{% extends "base.html" %}
{% block content %}

<div class="container mt-2 text-center">
    <div class="card p-3 d-inline-block">
        <h2 class="mt-4">Sign up</h2>
        <form method="post" class="mt-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
        <p class="text-center">¿Ya tienes cuenta? <a href="{% url 'login' %}" class="btn btn-link">Inicia sesión</a></p>

    </div>
</div>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block index %}
    <div class="jumbotron mt-5">
        <h1 class="display-4">Bienvenido a Mi Proyecto</h1>
        <p class="lead">Este es un ejemplo de una página principal con enlaces a la administración y a las encuestas.</p>
        <hr class="my-4">
        <p>Puedes comenzar explorando las siguientes opciones:</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'admin:index' %}" role="button">Administración</a>
            <a class="btn btn-success btn-lg" href="{% url 'polls:index' %}" role="button">Encuestas</a>
        </p>
    </div>
{% endblock %}

polls/templates/polls/base.html
<!DOCTYPE html>
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Álvaro Rodríguez Molina">
    <title>{% block title %}Tutorial{% endblock %}</title>
</head>
<body>
    <div class="container mt-4">
        {% include 'header.html' %}

        {% block index %}{% endblock %}

        {% block content %}{% endblock %}

        {% include 'footer.html' %}
    </div>
    
   </body>
</html>

polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h1>{{ question.question_text }}</h1>

        {% if question.comment %}
            <p><strong>Comment:</strong> {{ question.comment }}</p>
        {% endif %}
        <p><strong>Category:</strong> {{ question.get_category_display }}</p>
        <p><strong>Date Published:</strong> {{ question.pub_date }}</p>
        <p><strong>Created At:</strong> {{ question.created_at }}</p>
        <p><strong>Updated At:</strong> {{ question.updated_at }}</p>

        {% if error_message %}
            <div class="alert alert-danger mt-3" role="alert">
                <strong>{{ error_message }}</strong>
            </div>
        {% endif %}

        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend class="mt-3">Vote for a Choice</legend>
                {% for choice in question.choice_set.all %}
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                        <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                    </div>
                {% endfor %}
            </fieldset>
            <button type="submit" class="btn btn-primary mt-3">Vote</button>
        </form>
    </div>
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-4">
        <h1 class="mb-4">Latest Questions</h1>

        {% if latest_question_list %}
            <ul class="list-group">
                {% for question in latest_question_list %}
                    <li class="list-group-item">
                        <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                        <p class="mb-0">
                            <strong>Category:</strong> {{ question.get_category_display }} |
                            <strong>Date Published:</strong> {{ question.pub_date }} |
                            <strong>Created At:</strong> {{ question.created_at }} |
                            <strong>Updated At:</strong> {{ question.updated_at }}
                        </p>
                        {% if question.comment %}
                            <p><strong>Comment:</strong> {{ question.comment }}</p>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="mt-3">No polls are available.</p>
        {% endif %}
    </div>
{% endblock %}

polls/templates/polls/questions_list_pollsters_user.html
{% extends "base.html" %}

{% block content %}
    <h1>Preguntas del usuario</h1>

    {% if question_list %}
    <ul>

      {% for question in question_list %}
      <li class="{% if question.was_published_recently %}text-danger{% endif %}">
        <a href="{% url 'polls:detail' question.pk %}">{{question.question_text}}</a> ({{ question.pub_date }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No hay preguntas para este usuario.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h1>{{ question.question_text }}</h1>

        <ul class="list-group">
            {% for choice in question.choice_set.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ choice.choice_text }}
                    <span class="badge bg-primary rounded-pill">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span>
                </li>
            {% endfor %}
        </ul>

        <div class="mt-3">
            <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary">Vote again?</a>
            <a href="{% url 'polls:index' %}" class="btn btn-secondary">Back to Index</a>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Álvaro Rodríguez Molina">
    <title>{% block title %}Tutorial{% endblock %}</title>
</head>
<body>
    <div class="container mt-4">
        {% include 'header.html' %}

        {% block index %}{% endblock %}

        {% block content %}{% endblock %}

        {% include 'footer.html' %}
    </div>
   </body>
</html>

templates/footer.html
<footer class="mt-5">
    <div class="container text-center">
        <p>&copy; 2024 Mi Proyecto. Todos los derechos reservados.</p>
        <p><a href="https://github.com/alvrichh/Django-proyect"></a></p>
    </div>
</footer>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Mi Proyecto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav align-items-center">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">
                        <i class="bi bi-gear"></i> Administración
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'polls:index' %}">
                        <i class="bi bi-bar-chart-line"></i> Encuestas
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:myquestions' %}">
                            <i class="bi bi-file-earmark-text"></i> Mis Encuestas
                        </a>
                    </li>
                    <li class="nav-link"><i class="bi bi-person"></i> User: {{ user.get_username }}</li>
                    <li class="nav-item">
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button class="btn btn-link nav-link" type="submit">
                                <i class="bi bi-power"></i> Cerrar Sesión
                            </button>
                        </form>
                    </li>
                {% else %}
                    <li>
                        <a class="btn btn-link nav-link" href="{% url 'login' %}?next={{request.path}}">
                            <i class="bi bi-box-arrow-right"></i> Iniciar sesión
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>